# Generated by Django 5.0.4 on 2024-04-20 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('poste_type', models.IntegerField(choices=[(0, 'Offre'), (1, 'Demande')])),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('telnumber', models.IntegerField(blank=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('user_type', models.CharField(default='user', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social.poste')),
                ('intitule', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('lieu', models.CharField(max_length=255)),
                ('contact_Event', models.CharField(max_length=255)),
            ],
            bases=('social.poste',),
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social.poste')),
                ('localisation', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logment_contact', models.CharField(max_length=255)),
            ],
            bases=('social.poste',),
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social.poste')),
                ('texte', models.CharField(max_length=255)),
            ],
            bases=('social.poste',),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social.poste')),
                ('typeStg', models.IntegerField(choices=[(1, 'Ouvrier'), (2, 'Technicien'), (3, 'PFE')])),
                ('societe', models.CharField(max_length=255)),
                ('duree', models.IntegerField()),
                ('sujet', models.CharField(max_length=255)),
                ('contact_Stage', models.CharField(max_length=255)),
                ('specialite', models.CharField(choices=[('IT', 'IT - Technologie informatique'), ('SEG', 'SEG - Sc Eco et Gestion'), ('GC', 'GC - Génie Civil'), ('GP', 'GP - Génie des Procédés'), ('GM', 'GM - Génie Mécanique')], max_length=5)),
            ],
            bases=('social.poste',),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social.poste')),
                ('depart', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('heure_dep', models.TimeField()),
                ('nbre_sieges', models.IntegerField()),
                ('contact_Trans', models.CharField(max_length=255)),
            ],
            bases=('social.poste',),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=999)),
                ('like', models.BooleanField(default=False)),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.poste')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.user')),
            ],
        ),
        migrations.AddField(
            model_name='poste',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.user'),
        ),
        migrations.CreateModel(
            name='EvenClub',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social.evenement')),
                ('club', models.CharField(max_length=255)),
            ],
            bases=('social.evenement',),
        ),
        migrations.CreateModel(
            name='EvenSocial',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social.evenement')),
                ('prix', models.FloatField()),
            ],
            bases=('social.evenement',),
        ),
    ]
